#!/bin/sh

cd ~/.config/i3blocks/
# Push notification when low battery

BAT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
SENTBATMES=$(cat ./sent.txt)
COLOR1=""
COLOR2=""

normalize() {
	if [ $SENTBATMES -eq 0 ]
	then
		sh ~/.fehbg
		echo 1 > ./sent.txt
	fi
}

if [ ! -f "$STATUS" ]; 
then
	return
fi

if [ "$STATUS" = "Charging" ]
then
	normalize	
	COLOR1=""
elif [ $BAT -gt $1 ]
then
	normalize
	COLOR1=""
elif [ $SENTBATMES -eq 1 ]
then
	echo 0 > ./sent.txt
	notify-send -u critical "LOW BATTERY ($BAT%)" "Schauut dä schiss PC ab, oder steck nä ih!"	
	sh ~/.fehbgLOWBAT
	xbacklight -set 20
fi

#echo $COLOR1⚡$BAT%$COLOR2
echo $BAT%

