#!/bin/sh

cd ~/.config/polybar/
# Push notification when low battery

if [ ! -f "/sys/class/power_supply/BAT0/capacity" ]; 
then
	exit
fi

BAT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
SENTBATMES=$(cat ./sent.txt)
COLOR1=""
COLOR2=""

normalize() {
	if [ $SENTBATMES -eq 0 ]
	then
		sh ~/.fehbg
		echo 1 > ./sent.txt
	fi
}


if [ "$STATUS" = "Charging" ]
then
	normalize	
	COLOR1=""
elif [ $BAT -gt $1 ]
then
	normalize
	COLOR1=""
elif [ $SENTBATMES -eq 1 ]
then
	echo 0 > ./sent.txt
	notify-send -u critical "LOW BATTERY ($BAT%)" "Schauut dä schiss PC ab, oder steck nä ih!"	
	sh ~/.fehbgLOWBAT
	xbacklight -set 20
fi

if [ $BAT -gt 95 ]
then
	COLOR1=$COLOR1
elif [ $BAT -gt 70 ]
then
	COLOR1=$COLOR1
elif [ $BAT -gt 45 ]
then
	COLOR1=$COLOR1
elif [ $BAT -gt 20 ]
then
	COLOR1=$COLOR1
else
	COLOR1=$COLOR1
fi

#echo $COLOR1⚡$BAT%$COLOR2
echo $COLOR1 $BAT%

