#!/bin/sh

cd ~/.config/i3blocks/
# Push notification when low battery

BAT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)
SENTBATMES=$(cat ./sent.txt)
COLOR1="<span foreground='Tomato'>"
COLOR2="</span>"

normalize() {
	if [ $SENTBATMES -eq 0 ]
	then
		echo 1 > ./sent.txt
	fi
}

if [ ! -f "$STATUS" ]; 
then
	exit
fi

if [ "$STATUS" = "Charging" ]
then
	normalize	
	COLOR1="<span foreground='MediumSeaGreen'>"
elif [ $BAT -gt $1 ]
then
	normalize
	COLOR1="<span>"
elif [ $SENTBATMES -eq 1 ]
then
	echo 0 > ./sent.txt
	notify-send -u critical "LOW BATTERY ($BAT%)" "Schauut dä schiss PC ab, oder steck nä ih!"	
	xbacklight -set 20
fi

echo $COLOR1⚡$BAT%$COLOR2

